### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by creasty** [creasty-sandbox/delta_test#1]
- [ ] Load configuration from a file
  - perhaps, `yaml` ?
- [ ] Custom dependency mappings
  - Like `i18n-spec` and local files
- [ ] Run spec files regardless of the table if they're changed
- [ ] Add verbose option
  - output detailed logs for debugging purpose
- [ ] Create executable command
  - **Working in progress**
- [ ] Support parallel-tests
  - Thread safe programming maybe?
  - `at_exit` should wait for all processes to finish their tasks

---

- [ ] Write readme on usage & contributions
- [ ] Move to `creasty/delta_test` for a release as a gem

**Comment by creasty** [comment]
Configuration file sample:

```yaml
table_file: "/tmp/delta_test_tb"

files:
  - "app/models"
  - "app/controllers"

custom_dependencies:
  "spec/features/i18n_spec.rb":
    - "config/locales/**/*.yml"
```
