### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by creasty** [creasty-sandbox/delta_test#2]
Something like this:

```yaml
table_file: "/tmp/delta_test_tb"

files:
  - "app/models"
  - "app/controllers"

custom_dependencies:
  "spec/features/i18n_spec.rb":
    - "config/locales/**/*.yml"
```

**Comment by creasty** [comment]
Maybe we can define custom dependencies in spec files.

```ruby
describe "Something to describe", dependencies: ["config/locales/**/*.yml"] do

  it "should ...
```

**Comment by creasty** [comment]
Regexp

```yaml
table_file: "/tmp/delta_test_tb"

files:
  - "^app/models"
  - "^app/controllers"

custom_dependencies:
  "spec/features/i18n_spec.rb":
    - "^config/locales/.+\.yml"
```

```ruby
describe "Something to describe", dependencies: [%r{^config/locales/.+*\.yml}] do

  it "should ...
```
